
server:
  port: 8013
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doc_bank
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 15
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect